name: Update data

on:
  schedule:
     - cron: "*/15 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run the script
        run: python scripts/2_rss.py

      - name: Check for changes in cases.parquet
        run: |
          git diff --exit-code data/cases.parquet || echo "Changes detected"
        id: changes_detected
        continue-on-error: true

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes if cases.parquet is modified
        if: steps.changes_detected.outcome == 'failure'
        run: |
          BRANCH_NAME="update-terms-$(date +%Y%m%d%H%M)"
          git checkout -b "$BRANCH_NAME"
          git add data/cases.parquet
          git add data/files.parquet
          git commit -m "Update data on $(date +%Y-%m-%d)"
          git push origin "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: create pull request
        if: steps.changes_detected.outcome == 'failure'
        run:  |
          BRANCH_NAME="update-terms-$(date +%Y%m%d%H%M)"
          gh pr create -B base_branch -H branch_to_merge --title 'Update data on $(date +%Y-%m-%d)' --body 'Created by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
